version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # app
      - ./nginx/src:/usr/share/nginx/html
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      # certificates
      - ./nginx/cart/server.crt/:/etc/nginx/server.crt:ro
      - ./nginx/cart/server.key/:/etc/nginx/server.key:ro

  # php-fpm
  fpm:
    build: ./php-fpm
    ports:
      - "9000"
    volumes:
      - ./nginx/src:/usr/share/nginx/html
      # Your php.ini
      - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
    # environment:
      # Set your APP env variables here:
      # - APP_KEY=
      # - DB_HOST=
      # - DB_DATABASE=
      # - DB_USERNAME=
      # - DB_PASSWORD=
    links:
      - mariadb:mariadb

  # database
  mariadb: 
    image: mariadb:latest
    ports:
      # Allow client to access 3306
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<your_mysql_password>
